### ISSUE TITLE
Update Coinbase Tax Collector to include "losses"

### ISSUE THREAD

**Issue by mdoming10** [ydeleon6/coinbase-tax-collector#3]
Presently, all CTC results are listed as "gains" in all circumstances.  The script should be updated so calculations are listed as "losses" whenever relevant.

**Comment by ydeleon6** [comment]
Good suggestion, I will put up a PR for this by the end of this week!

**Comment by ydeleon6** [comment]
Hi @mdoming10  please check out this PR where I implement this. Let me know if this looks like what you expect with "Losses" vs. "Gains"!

https://github.com/ydeleon6/coinbase-tax-collector/pull/5
